# Generated by Django 6.0.1 on 2026-01-17 06:55

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('pattern_position', models.IntegerField(default=0, help_text='Position in rotation pattern (0-3)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'ordering': ['pattern_position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EM', 'Early Morning Monitoring (Server Status)'), ('DM', 'Daily Monitoring (Events/Incidents)')], max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_start_hour', models.IntegerField(default=17, help_text='5 PM = 17')),
                ('default_start_minute', models.IntegerField(default=0)),
                ('default_end_hour', models.IntegerField(default=7, help_text='7 AM = 7')),
                ('default_end_minute', models.IntegerField(default=0)),
                ('monday_start_offset_hours', models.IntegerField(default=0, help_text='Hours to extend start time back for Monday')),
                ('monday_end_offset_hours', models.IntegerField(default=0, help_text='Hours to extend end time forward for Monday')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOC Monitoring Pattern', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reference_start_date', models.DateField(default=datetime.date.today)),
                ('em_pattern', models.JSONField(default=list, help_text='EM rotation pattern [0,1,2,3,0,1,2,...]')),
                ('dm_pattern', models.JSONField(default=list, help_text='DM rotation pattern [3,0,1,2,3,0,1,...]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('duration_hours', models.FloatField(editable=False)),
                ('is_monday_assignment', models.BooleanField(default=False)),
                ('is_extended_window', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('report_submitted', models.BooleanField(default=False)),
                ('report_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('report_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schedule_app.analyst')),
                ('report_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to='schedule_app.analyst')),
                ('monitoring_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.monitoringtype')),
            ],
            options={
                'ordering': ['date', 'monitoring_type__code'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('VACATION', 'Vacation'), ('SICK', 'Sick Leave'), ('PERSONAL', 'Personal Leave'), ('TRAINING', 'Training'), ('OTHER', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('emergency_contact', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('coverage_notes', models.TextField(blank=True)),
                ('auto_adjust_pattern', models.BooleanField(default=True, help_text='Automatically adjust rotation pattern during leave')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='schedule_app.analyst')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_approved', to='schedule_app.analyst')),
                ('covered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_assignments', to='schedule_app.analyst')),
                ('affected_assignments', models.ManyToManyField(blank=True, related_name='affected_by_leave', to='schedule_app.monitoringassignment')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('SCHEDULE_CHANGE', 'Schedule Change'), ('SWAP_REQUEST', 'Swap Request'), ('SWAP_APPROVED', 'Swap Approved'), ('LEAVE_APPROVED', 'Leave Approved'), ('REPORT_DUE', 'Report Due'), ('SHIFT_REMINDER', 'Shift Reminder'), ('SYSTEM', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schedule_app.analyst')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='monitoring_reports/%Y/%m/%d/')),
                ('summary', models.TextField()),
                ('critical_issues', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('completeness_score', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('timeliness_score', models.IntegerField(default=100, help_text='Score based on submission time vs deadline', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_submission', to='schedule_app.monitoringassignment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='schedule_app.analyst')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='schedule_app.analyst')),
            ],
            options={
                'verbose_name': 'Report Submission',
                'verbose_name_plural': 'Report Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SOC Schedule Generator', max_length=100)),
                ('auto_generate', models.BooleanField(default=True)),
                ('generate_days_ahead', models.IntegerField(default=30)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('enforce_pattern', models.BooleanField(default=True)),
                ('allow_manual_overrides', models.BooleanField(default=False)),
                ('require_approval_for_changes', models.BooleanField(default=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule_app.schedulepattern')),
            ],
            options={
                'verbose_name': 'Schedule Generator',
                'verbose_name_plural': 'Schedule Generators',
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('reason', models.TextField()),
                ('swap_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_approved', to='schedule_app.analyst')),
                ('original_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_outgoing', to='schedule_app.monitoringassignment')),
                ('reciprocal_assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_swap', to='schedule_app.monitoringassignment')),
                ('requested_analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='schedule_app.analyst')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='schedule_app.analyst')),
            ],
            options={
                'verbose_name': 'Shift Swap Request',
                'verbose_name_plural': 'Shift Swap Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitoringassignment',
            index=models.Index(fields=['date', 'analyst'], name='schedule_ap_date_015306_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringassignment',
            index=models.Index(fields=['status', 'date'], name='schedule_ap_status_7a2a4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringassignment',
            unique_together={('date', 'monitoring_type')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='schedule_ap_recipie_a18997_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for', 'notification_type'], name='schedule_ap_schedul_1486d8_idx'),
        ),
    ]
