# Generated by Django 6.0.1 on 2026-01-17 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyst',
            options={'ordering': ['pattern_position', 'display_name'], 'verbose_name': 'SOC Analyst', 'verbose_name_plural': 'SOC Analysts'},
        ),
        migrations.AlterModelOptions(
            name='monitoringassignment',
            options={'ordering': ['date', 'monitoring_type__code'], 'verbose_name': 'Monitoring Assignment', 'verbose_name_plural': 'Monitoring Assignments'},
        ),
        migrations.AlterModelOptions(
            name='monitoringtype',
            options={'verbose_name': 'Monitoring Type', 'verbose_name_plural': 'Monitoring Types'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='schedulepattern',
            options={'verbose_name': 'Schedule Pattern', 'verbose_name_plural': 'Schedule Patterns'},
        ),
        migrations.RenameField(
            model_name='analyst',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='analyst',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyst_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitoringtype',
            name='default_end_hour',
            field=models.IntegerField(default=7, help_text='7 AM = 7 (24-hour format)'),
        ),
        migrations.AlterField(
            model_name='monitoringtype',
            name='default_start_hour',
            field=models.IntegerField(default=17, help_text='5 PM = 17 (24-hour format)'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['analyst', 'status'], name='schedule_ap_analyst_4c36e4_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='schedule_ap_start_d_6d73db_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringassignment',
            index=models.Index(fields=['analyst', 'date'], name='schedule_ap_analyst_dd7267_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftswaprequest',
            index=models.Index(fields=['status', 'expiry_date'], name='schedule_ap_status_b283e6_idx'),
        ),
    ]
